#!/bin/bash

set -e
source /usr/share/yunohost/helpers

app=${app:?}
install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)

if [ -f "$install_dir/docker-compose.yml" ]; then
  cd "$install_dir"
  docker compose down || true
fi

ynh_remove_nginx_config
