#!/bin/bash

set -e
source /usr/share/yunohost/helpers

app=${app:?}
install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)

cd "$install_dir"
if command -v docker-compose >/dev/null 2>&1; then
  docker-compose pull
  docker-compose up -d
else
  docker compose pull
  docker compose up -d
fi
